In [1]:
import numpy as np
from sklearn.datasets import fetch_california_housing
import tensorflow as tf

In [2]:
housing = fetch_california_housing()
m, n = housing.data.shape
housing_plus_bias = np.c_[np.ones((m, 1)), housing.data]
m, n

(20640, 8)

In [3]:
X = tf.constant(housing_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")


In [4]:
n_epochs = 50
learning_rate = 0.01

theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")

y_pred = tf.matmul(X, theta, name="predictions")

error = y_pred - y

mse = tf.reduce_mean(tf.square(error), name="mse")

# optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)

# training_op = optimizer.minimize(mse)

gradients = (tf.matmul(tf.transpose(X), error)/m)*2

training_op = tf.assign(theta, theta - learning_rate * gradients)

In [6]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(n_epochs):
        #if(epoch %100 == 0):
        #print "Epoch", epoch
        print "Error", sess.run(error)
        #print "MSE", sess.run(mse)
        #print "Theta", theta.eval()
        #print "gradients", sess.run((tf.matmul(tf.transpose(X), error)/m)*2)
        print "gradients\n",sess.run(gradients)
        #print type(gradients)
        #print gradients.dtype
        #print "learning rate", learning_rate
        #print "Multiplied by learning rate\n", sess.run(gradients * learning_rate)
        print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    best_theta = theta.eval()
    print best_theta
    

Error [[  69.92973328]
 [ 633.296875  ]
 [ 108.33477783]
 ..., 
 [ 268.5401001 ]
 [ 198.22544861]
 [ 369.38595581]]
gradients
[[  7.33512451e+02]
 [  2.85200513e+03]
 [  1.85172578e+04]
 [  3.89536133e+03]
 [  7.88185608e+02]
 [  1.72475062e+06]
 [  2.47077295e+03]
 [  2.60037031e+04]
 [ -8.75869141e+04]]
('Epoch', 0, 'MSE =', 224647.67)
Error [[ -5678714.5]
 [-41531956. ]
 [ -8681807. ]
 ..., 
 [-17487866. ]
 [-12900379. ]
 [-24041662. ]]
gradients
[[ -4.94105200e+07]
 [ -1.91609856e+08]
 [ -1.26951757e+09]
 [ -2.61270080e+08]
 [ -5.29617480e+07]
 [ -1.14667512e+11]
 [ -1.80071952e+08]
 [ -1.75152179e+09]
 [  5.90020250e+09]]
('Epoch', 1, 'MSE =', 9.9178848e+14)
Error [[  3.77659294e+11]
 [  2.76130326e+12]
 [  5.77319272e+11]
 ..., 
 [  1.16276514e+12]
 [  8.57773048e+11]
 [  1.59848451e+12]]
gradients
[[  3.28520932e+12]
 [  1.27397611e+13]
 [  8.44084973e+13]
 [  1.73713643e+13]
 [  3.52133002e+12]
 [  7.62381767e+15]
 [  1.19725244e+13]
 [  1.16455354e+14]
 [ -3.92293085e+14]]
('E

[[ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]
 [ nan]]


In [25]:
a = tf.Variable([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print sess.run(a)
    print sess.run(a * 0.1)

[[ 1.  2.]
 [ 3.  4.]]
[[ 0.1         0.2       ]
 [ 0.30000001  0.40000001]]
