<h2>Tensors</h2>
<p>
    Data is handled in objects called tensors represented by <b>tf.Tensor</b>. They can be treated as n-dimensional arrays TensorFlow programs first build a comutational graph of <b>tf.Tensor</b> objects. Each tensor has the the properties data type and shape. Each element is of the same data type.
</p>
Types of tensors:
<ul>
    <li>tf.Variable</li>
    <li>tf.constant</li>
    <li>tf.placeholder</li>
    <li>tf.SparseTensor</li>
</ul>

<p>
    With the exception of tf.Variable, the value of tensor is immutable.
</p>

In [1]:
import tensorflow as tf
import numpy as np

<h2>Rank</h2>
<p>Rank of a tensor is the number of dimensions it contains.</p>

In [15]:
# Rank 0
mammal = tf.Variable("Elephant", tf.string) # string
ignition = tf.Variable(451, tf.int16) # integer
floating = tf.Variable(3.14159265359, tf.float64) # float
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64) # complex numbers

sess = tf.Session()
tf.global_variables_initializer()

# find the rank using tf.rank
print sess.run(tf.rank(mammal))

# rank 1
rank1_int = tf.Variable([451, 78], tf.int16)
print sess.run(tf.rank(rank1_int))

# rank 2
rank2_int = tf.Variable([[23], [98]])
print sess.run(tf.rank(rank2_int))

0
1
2


In [27]:
# python indexing and slicing

squares = tf.Variable([ [4, 9, 1], [16, 25, 64], [36, 49, 81] ], tf.int32)
sess.run(squares.initializer)

print sess.run(squares[0, 0])
print sess.run(squares[1, 1])
print sess.run(squares[:, 1])
print sess.run(squares[:, 0:1])
print sess.run(squares[1:2, :])

4
25
[ 9 25 49]
[[ 4]
 [16]
 [36]]
[[16 25 64]]


In [29]:
# shape

print sess.run(tf.shape(squares))
print sess.run(tf.shape(squares[1:2, :]))

[3 3]
[1 3]


In [31]:
# Evaluating Tensors
# use eval() of a tensor. Works when a default tf.Session is active

constant = tf.constant([1, 2, 3])
tensor = constant * constant
print sess.run(tensor.eval())

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`